---
driver:
  name: vagrant
  
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - "recipe[apt::default]"
    - "recipe[rundeck::node_unix]"
suites:
  - name: default
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - "recipe[rundeck::server]"
      - "recipe[create_chef_dir]"
      - "recipe[rundeck::chef-rundeck]"
    attributes:
      rundeck:
        hostname: 'localhost'
        security_roles: ['superusers', 'run_only_users']
        secret_file: '/tmp/kitchen/encrypted_data_bag_secret'
      domain: 'kitchentest'
  - name: rdbms
    encrypted_data_bag_secret_key_path: 'test/integration/rdbms/encrypted_data_bag_secret'
    run_list:
      - "recipe[rundeck::server]"
      - "recipe[create_chef_dir]"
    attributes:
      rundeck:
        hostname: 'localhost'
        security_roles: ['superusers', 'run_only_users']
        rdbms:
          enable: true
        secret_file: 'tmp/kitchen/encrypted_data_bag_secret'
      domain: 'kitchentest'
